# {{workshopTitle}}

{{description}}

- **Author:** {{author}}
- **Build target:** {{buildTag}} (`{{buildTarget}}`)
- **Mod ID:** `{{modId}}`
- **Created:** {{createdAt}}

Generated by [Project Zomboid Mod Creator](https://github.com/zjdaniels1985/pz-mod-creator).

---

## Project layout

```
{{projectFolderName}}/
|
+-- .pzmodcreator.json     Project manifest. Tracks mods, author, and build
|                          target. Managed by the extension - edit via the
|                          PZ Mods view rather than by hand.
|
+-- .types/                Downloaded Lua API stubs, for IntelliSense only.
|   +-- candle/            Vanilla PZ API definitions.
|   +-- pzeventdoc/        Event signature definitions.
|
+-- .vscode/
|   +-- settings.json      Lua language server config (library paths, globals).
|   +-- extensions.json    Recommends the sumneko.lua extension.
|
+-- preview.png            Workshop listing image. Replace the placeholder.
|                          Steam recommends 512x512 or larger.
|
+-- workshop.txt           Steam Workshop metadata for the whole project.
|
+-- README.md              This file.
|
+-- {{modsRootLabel}}/
    +-- {{modId}}/
        |
        +-- mod.info       Root manifest. Used for mod discovery.
        |
        +-- poster.png     In-game mod list thumbnail. Replace the placeholder.
        |
        +-- {{versionFolderPath}}
            +-- mod.info   Declares versionMin={{versionMin}} for this content set.
            |
            +-- media/
                |
                +-- lua/
                |   +-- client/{{modId}}/    Client-only code: UI, rendering, input.
                |   +-- server/{{modId}}/    Server-only code: authoritative logic.
                |   +-- shared/{{modId}}/    Code loaded on both sides.
                |   +-- shared/Translate/    Translation files, one folder per
                |                            language code.
                |
                +-- scripts/   Item, recipe, and vehicle definitions (.txt).
                |
                +-- textures/  Item icons and world textures (.png).
```

{{layoutNotes}}

### Build 42 layout notes

Build 42 loads mod content from a **version folder** such as `{{versionFolder}}/`
rather than from `media/` at the mod root. The game scans `mods/<ModId>/` for
version folders, picks the closest match for the running game build, and reads
that folder's `mod.info` and `media/`.

This has two consequences worth knowing:

- The **root** `mod.info` must not contain `versionMin=`. It is a discovery
  stub. The **version folder's** `mod.info` declares `versionMin`.
- Build 41 mods, which put `media/` at the mod root with no version folder, are
  rejected by Build 42. The log line is `refusing to list <modid>`.

If you later need to ship different content for a newer patch, add a sibling
folder (for example `42.13/`) with its own `mod.info` and `media/`. Assets that
never change between versions can live in a `common/media/` folder at the mod
root.

### Why client / server / shared

Project Zomboid loads these three folders in different contexts, and getting
it wrong is the most common source of multiplayer bugs.

| Folder   | Loaded on            | Use for                                      |
| -------- | -------------------- | -------------------------------------------- |
| `client` | Client only          | UI, ISPanel windows, key bindings, rendering |
| `server` | Server only          | Authoritative state, anti-cheat, spawning    |
| `shared` | Both client + server | Utilities, constants, translations           |

In single-player the game runs an internal server, so all three load. This
means a `server` file containing a UI call may work fine solo and then break in
multiplayer.

## Building

Run **PZ Mod Creator: Build** from the Command Palette. Files are copied to:

```
{{outputPathExample}}
```

Use **Build and Watch** while developing to sync changes automatically as you
save.

Files matching the ignore globs in your settings - `.git`, `node_modules`,
`.types`, `.vscode`, and `.pzmodcreator.json` - are excluded from the build.
The `.types` folder is IntelliSense scaffolding and must never ship.

## Testing in game

The `Zomboid/Workshop/` folder is the **upload staging** area. For local
testing, copy the mod folder into `Zomboid/mods/` instead:

```
Zomboid/mods/{{modId}}/
```

Note that this is the mod folder itself, without the `{{modsRootLabel}}/`
wrapper. Then:

1. Launch Project Zomboid, open **Mods**, and enable this mod.
2. Start or load a save.
3. Check `Zomboid/console.txt` for `[{{modId}}]` log lines from the starter
   Lua files, and for any errors.

Fully exit the game between tests - mods are enumerated at startup only, and
returning to the main menu is not enough.

### If the mod does not appear in the list

- Search `console.txt` for `refusing to list {{modId}}`. If present, the folder
  structure is wrong for your game build - see the Build 42 notes above.
- If there is no mention of the mod at all, it is not being scanned. Check that
  you copied it to the right `Zomboid` directory and that you launched the game
  build matching this project's target.
- `mod.info` `id=` must match the mod folder name exactly, including case.
- Empty fields in `mod.info` can hide a mod. A blank `require=` in particular is
  read as a dependency on a mod with an empty ID.

## Publishing to the Steam Workshop

1. Run **Build** so the project is in `Zomboid/Workshop/`.
2. Launch the game, open **Workshop**, then **Create and Update Item**.
3. Select this project and upload.

Steam assigns a numeric Workshop ID on first upload and writes it into the
`id=` field of `workshop.txt` **in the build output folder**.

> **Important:** copy that ID back into this project's `workshop.txt` before
> your next build. Otherwise the build overwrites the output copy with a blank
> `id=`, and the following upload creates a duplicate Workshop listing instead
> of updating the existing one.

Set `visibility=private` in `workshop.txt` for the first upload while you
verify the listing, then switch it to public.

## Translations

Translation files live in `media/lua/shared/Translate/<LANG>/`. Use
**PZ Mod Creator: Add Translation Language** to create a new language folder,
or **Copy Translation Language** to duplicate an existing one and rewrite its
headers to the new language code.

Each file declares a table whose name ends in the language code, for example
`IG_UI_EN` in `IG_UI_EN.txt`. The code must match the folder name.

## Credits

The Lua IntelliSense in this project is powered by two community-maintained
definition projects. Neither is affiliated with this extension or with The
Indie Stone - they are downloaded into `.types/` purely to give the language
server something to autocomplete against, and are never included in builds.

### [Candle](https://github.com/asledgehammer/Candle) - by [asledgehammer](https://github.com/asledgehammer)

Generated Lua API definitions covering the vanilla Project Zomboid Java classes
exposed to Lua. This is what makes `getPlayer()`, `ISPanel`, and the rest of the
API resolve with real type information instead of showing up as unknown globals.

Candle does not currently publish a license. The files fetched into `.types/`
are downloaded from the upstream repository for local editor use only. Do not
redistribute them or include them in a published mod without permission from
the authors.

### [PZEventDoc](https://github.com/demiurgeQuantified/PZEventDoc) - by [demiurgeQuantified](https://github.com/demiurgeQuantified)

Documented signatures for the `Events` system, so `Events.OnGameStart.Add(...)`
and friends carry correct parameter names and types.

Licensed under the MIT License. See the upstream repository for the full text.

### Supporting them

If these definitions save you time, consider giving the repos a star, reporting
gaps or inaccuracies you hit while modding, or contributing fixes upstream.
Accurate stubs benefit everyone modding Project Zomboid, and both projects are
maintained on volunteer time.

Run **PZ Mod Creator: Update Definitions** periodically to pull the latest
versions - the PZ API changes between builds, and these projects track it.

## Notes

- Changing a mod ID after publishing breaks existing saves that reference it.
- `mod.info` `id=` must match the mod's folder name exactly.
- Mod IDs are case-sensitive in game, and Linux servers have case-sensitive
  filesystems, so keep casing consistent.